Railway-master/railway/Railway/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views

from trains.forms import LoginForm
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('trains.urls')),
    re_path(r'^oauth/', include('social_django.urls', namespace='social'))
]

urlpatterns += staticfiles_urlpatterns()

Railway-master/railway/trains/urls.py
from django.urls import path
from .views import AllTrainsListView,Bookings,TrainsDetailView,LogoutUserView,showHome
from .views import search,RegisterView, login_page,profile,BookingCancelDetailView, confirm_cancel,confirm_booking, ticket


urlpatterns = [
    # path('',HomeTemplateView.as_view(),name = 'home'),
    path('', showHome, name='home'),
    path('all/',AllTrainsListView.as_view(),name = 'all_trains'),
    path('all_booked/',Bookings.as_view(),name = 'all_booked'),
    path('trains/<int:pk>',TrainsDetailView.as_view(),name ='trains'),
    path('Ticket/',ticket,name='Ticket'),
    path('search/',search,name='search'),
    path('Register/',RegisterView.as_view(),name='Register'),
    path('login/',login_page,name='login'),
    path('logout/',LogoutUserView.as_view(),name='logout'),
    path('user/<slug:username>/',profile.as_view(),name='profile'),
    path('booking/<int:pk>/',BookingCancelDetailView.as_view(),name='cancel'),
    path('confirm_cancel/<int:pk>',confirm_cancel,name='confirm_cancel'),
    path('buy/<int:pk>',confirm_booking,name ='confirm_booking'),

]

Railway-master/railway/trains/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,BaseUserManager,PermissionsMixin
from django.contrib.auth.models import User
# Create your models here.

class Trains(models.Model):
    categories = (
        ('Normal','Normal'),
        ('Express','Express')
    )
    id = models.AutoField(primary_key=True)
    source = models.CharField(max_length = 30,)
    destination = models.CharField(max_length = 30)
    seats_total = models.IntegerField()
    seats_res = models.IntegerField()
    types = models.CharField(choices=categories,max_length=20)
    cost = models.IntegerField()
    date = models.DateField()
    def __str__(self):
        return str(self.id)


class Users(AbstractUser):
    username = models.CharField(primary_key = True,max_length=20)
    email = models.EmailField(null=True)
    first_name = models.CharField(null=True,max_length = 20)
    last_name = models.CharField(null=True,max_length = 20)
    phone = models.CharField(null=True,max_length=10)
    aadharid = models.CharField(null=True,max_length=4)
    address = models.CharField(null=True, max_length=150)
    balance = models.IntegerField(default = 0)
    is_staff = models.BooleanField(default=False)
    USERNAME_FIELD = "username"
    def __str__(self):
        return self.username
 
class Booking(models.Model):
    id = models.AutoField(primary_key=True)
    num_booked = models.IntegerField()
    users = models.ForeignKey(Users,null=True,on_delete = models.CASCADE)
    trains = models.ForeignKey(Trains,null=True,on_delete=models.CASCADE)
    def __str__(self):
        return str(self.id)

Railway-master/railway/templates/Register.html
{% extends "base.html" %}
{% block title %} Register Page {% endblock title%}
{% block content %}
    <div class="form-content my-3 p-3">
		<div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-7">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-5">
                        <div class="card-header justify-content-center">
                        	<h2 class="font-weight-light my-4 text-center">Create Account</h2>
                        </div>
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                {% if form.errors %}
                                    <div class="alert alert-danger alert-dismissible" role="alert">
                                        <div id="form_errors">
                                            {% for key, value in form.errors.items %}
                                                <strong>{{ value }}</strong>
                                            {% endfor %}
                                        </div>
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                {% endif %}
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1">First Name</label>
                                            {{ form.first_name }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1">Last Name</label>
                                            {{ form.last_name }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-6">
		                                <div class="form-group">
		                                	<label class="small mb-1">Username</label>
		                                    {{ form.username }}
		                                </div>
		                            </div>
                                    <div class="col-md-6">
		                                <div class="form-group">
		                                	<label class="small mb-1">Email</label>
		                                    {{ form.email }}
		                                </div>
		                            </div>
		                        </div>
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1">Password</label>
                                            {{ form.password1 }}
                                            {{ form.errors.password }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">

                                        <div class="form-group">
                                            <label class="small mb-1">Confirm Password</label>
                                            {{ form.password2 }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1">Phone Number</label>
                                            {{ form.phone }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1">AADHAAR ID (last 4 digits)</label>
                                            {{ form.aadharid }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1">Permanent Address</label>
                                            {{ form.address }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group mt-4 mb-0">
                                    <button type="submit" class="col-md-12 btn btn-dark">Sign Up</button><br><br>
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'login' %}">Have an account? Go to Sign in</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
	</div>
{% endblock content %}

Railway-master/railway/templates/Ticket.html
{% extends "layout.html" %} {% block content%}
<div class="container my-4">
    <div class="main-body">
        <h3 class="font-weight-light my-1 text-center">Ticket Booking Page</h3>
        <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center">
                            <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
                            <div class="mt-3">
                                <h4>{{user.first_name| title}} {{user.last_name| title}}</h4>
                             <p class="text-secondary mb-1">{% if user.is_superuser %} ADMINISTRATOR {% else %}
                                Passenger {% endif %} </p>
                             <p class="text-muted font-size-sm">{% if user.is_active %}Online{% else %} Offline {% endif %}</p>
                             <h5 class=" text-primary-dark ">E-wallet balance : {{user.balance}} 
                             </h5>
                             <hr> <h5 class=" small mb-1">Click below to Recharge your E-wallet!</h5>
                                        <hr>
                                        <button class="btn btn-dark">Recharge Your Wallet</button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-md-8">
                <div class="card mb-3">
                    <div class="card-body">
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Unique ID : </h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                               <h6 id="demo"></h6>
                               <h6>
                                <script>
                                    
                                const characters ='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
                                function generateString(length) {
                                let result = ' ';
                                const charactersLength = characters.length;
                                for ( let i = 0; i < length; i++ ) {
                                   result += characters.charAt(Math.floor(Math.random() * charactersLength));
                                      }

                                return result;
                                 }

                                let s=generateString(12);
                                document.getElementById("demo").innerHTML = s;
                                </script>
                               </h6>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">NAME :</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{user.first_name| title}} {{user.last_name| title}}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">AADHAAR ID : </h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                              XXXX XXXX {{user.aadharid}}
                            </div>
                        </div>
                        <hr>
                        <div class="form-row">
                            <div class="col-sm-3">
                                <div class="form-group">
                                    <label class="small mb-1">First Name</label>
                                    {{ form.first_name }}
                                </div>
                            </div>
                        <hr>
                        <label for="name"><b>Activity Name:</b></label>          
                            <select name="activity" id="activity" required>
                            <script>
                                function getActivity(tx) {
                                    tx.executeSqllite('SELECT * FROM trains_trains', [], queryActivity, errorHandler);
                                        function queryActivity(tx, results) {
                                    var len = results.rows.length;
                                    for (var i = 0; i < len; i++) {
                                       var SelectActivity +='<option value="' + results.rows.item(i).activityID+'">'+ results.rows.item(i).ActivityName +'</Option>';
                                    }
                                    //SelectActivity +="</Option";
                                    document.getElementById("activity").innerHTML =SelectActivity;
                                }}
                            </script>
                            </select>
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="small mb-1">Last Name</label>
                                    {{ form.last_name }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Phone Number :</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{user.phone}}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Address</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{user.address}}
                            </div>
                        </div>
                        <hr>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>
</div> {% endblock content %}

Railway-master/railway/templates/all.html
{% extends "layout.html" %} {% block content%}
<div class=" p-5">
    <table class="table table-borderless table-hover">
        <thead class="text-center">
            <th>Source</th>
            <th>Destination</th>
            <th>Type</th>
            <th>Date</th>
        </thead>
        {% for train in Trains %}

        <tr class="text-center">
            <td>{{train.source}}</td>
            <td> {{train.destination}}</td>
            <td>{{train.types}}</td>
            <td> {{train.date}}</td>
            <td>
                <a href='{% url "trains" train.id %}'>
                    <button type="button" class="btn btn-primary">
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                        BOOK

                </button>
                </a>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock content %}

Railway-master/railway/templates/all_booked.html
{% extends "layout.html" %} {% block content%}

<div class=" p-5">

    <table class="table table-borderless table-hover">
        <thead>
            <th>Train id</th>
            <th>Booked TIckets</th>
            <th>Source</th>
            <th>Destination</th>
            <th>Type</th>
            <th>Date</th>

        </thead>
        {% for booking in Bookings %}
        <tr>
            <td>{{booking.trains.id}}</td>
            <td>{{booking.num_booked}}</td>
            <td>{{booking.trains.source}}</td>
            <td>{{booking.trains.destination}}</td>
            <td>{{booking.trains.types}}</td>
            <td> {{booking.trains.date}}</td>
            <td>
                <a href='{% url "cancel" booking.id %}'>
                    <button type="button" class="btn btn-danger">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-x-fill" viewBox="0 0 16 16">
                            <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zM7.354 5.646 8.5 6.793l1.146-1.147a.5.5 0 0 1 .708.708L9.207 7.5l1.147 1.146a.5.5 0 0 1-.708.708L8.5 8.207 7.354 9.354a.5.5 0 1 1-.708-.708L7.793 7.5 6.646 6.354a.5.5 0 1 1 .708-.708z"/>
                          </svg>
                        Cancel 

                </button>
                </a>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>


<a href='{% url "home" %}'>
    <button type="button " class="btn btn-primary ">
        <svg xmlns="http://www.w3.org/2000/svg " width="16 " height="16 " fill="currentColor " class="bi bi-arrow-left-circle " viewBox="0 0 16 16 ">
            <path fill-rule="evenodd " d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z "/>
          </svg>
        Go To Home

</button>
</a>
{% endblock content %}

Railway-master/railway/templates/avail.html
{% extends "layout.html" %} {% block content%}

<div class="p-5">

<form action="{{url_for('available')}}" method="POST">
    {{form.date.label}}{{form.date}}
    <input type="submit" value="Submit"></input>
</form>
</div>

{% if submitted %}

<div class="p-5">
    <table class="table table-borderless table-hover">
        <thead>
            <th>Train Id</th>
            <th>Source</th>
            <th>Destination</th>
            <th>Total seats</th>
            <th>Reserved seats</th>
            <th>Type</th>
            <th>Cost</th>
            <th>Date</th>
    
        </thead>
    
        {% for row in rows %}
        <tr>
            <td>{{row[0]}}</td>
            <td>{{row[1]}}</td>
            <td> {{row[2]}}</td>
            <td>{{row[3]}}</td>
            <td>{{row[4]}}</td>
            <td>{{row[5]}}</td>
            <td> {{row[6]}}</td>
            <td>{{row[7]}}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endif %}

{% endblock content %}

Railway-master/railway/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!--Font awesome icons -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

    <title>{% block title %} {% endblock %} </title>
</head>
<body>
  <div class="container p-3 my-3">
    <div class="row">
      <div class="col-md-12">
        <nav class="navbar navbar-expand-md navbar-light " style="background-color: #f0f5f5">
          <a href="/" class="navbar-brand">Home</a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav ml-auto">
                  {% if user.is_authenticated %}
                    <a href="{% url 'users-profile' %}" class="nav-item nav-link">Profile</a>
                    <a href="{% url 'logout' %}" class="nav-item nav-link">Logout</a>
                  {% else %}
                    <a href="{% url 'login' %}" class="nav-item nav-link">Sign in</a>
                  {% endif %}

                </div>
            </div>
        </nav>
        <!--Any flash messages pop up in any page because this is the base template-->
        {% if messages %}
          <div class="alert alert-dismissible" role="alert">
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endif %}
        {% block content %}{% endblock %}
      </div>
    </div>
  </div>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- A plugin for password show/hide  -->
    <script src="https://unpkg.com/bootstrap-show-password@1.2.1/dist/bootstrap-show-password.min.js"></script>

</body>
</html>

Railway-master/railway/templates/booking_cancel.html
{% extends 'layout.html' %}{% block content %}

<h1>Balance : {{booking.users.balance}}</h1>
<div class=" p-5">
    <table class="table table-borderless table-hover">
        <thead class="text-center">
            <th>Train Id</th>
            <th>Source</th>
            <th>Destination</th>
            <th>Total seats</th>
            <th>Reserved seats</th>
            <th>Type</th>
            <th>Cost</th>
            <th>Date</th>

        </thead>

        <tr class="text-center">
            <td>{{ booking.trains.id}}</td>
            <td>{{booking.trains.source}}</td>
            <td> {{booking.trains.destination}}</td>
            <td>{{booking.trains.seats_total}}</td>
            <td>{{booking.trains.seats_res}}</td>
            <td>{{booking.trains.types}}</td>
            <td>{{booking.trains.cost}}</td>
            <td> {{booking.trains.date}}</td>
        </tr>
    </table>
</div>

<a href='{% url "confirm_cancel" booking.id %} '><button type="button" class="btn btn-danger btn-lg btn-block">Confirm Cancellations</button> </a> {% endblock %}

Railway-master/railway/templates/profile.html
{% extends "layout.html" %} {% block content%}
<div class="container my-4">
    <div class="main-body">
        <h3 class="font-weight-light my-3 text-center"> | User Profile |</h3> <hr>
        <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center">
                            <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
                            <div class="mt-3">
                                <h4>{{user.first_name| title}} {{user.last_name| title}}</h4>
                             <p class="text-secondary mb-1">{% if user.is_superuser %} ADMINISTRATOR {% else %}
                                Passenger {% endif %} </p>
                             <p class="text-muted font-size-sm">{% if user.is_active %}Online{% else %} Offline {% endif %}</p>
                             <hr> <h5 class=" small mb-1">Click below to Recharge your E-wallet!</h5>
                             <hr>
                            <button class="btn btn-dark">Recharge Your Wallet</button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-md-8">
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">User Name</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{user.username}}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Email</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{user.email}}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Date Joined</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{user.date_joined}}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Phone Number</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{user.phone}}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">AADHAAR ID</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{user.aadharid}}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Address</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{user.address}}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">E-wallet Balance</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{user.balance}}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Current Bookings</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{user.booking_set.count}}
                            </div>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>
</div> {% endblock content %}

Railway-master/railway/templates/search.html
{% extends "layout.html" %} {% block content%}

<div class="no-gutters search_page_main">

    <h4 class="text-center p-4 border-bottom">Search a Train for your needs.</h4>

    <div class="d-flex justify-content-around mb-5 mt-5 " id="search_form">
    <form method="get" >     

            <input  id="id_source" name="source" type="text" placeholder="Source" />

            
            <input id="id_destination" name="destination" type="text" placeholder="Destination" />    

            
            
            <select name="types" id="id_types">
                {% for type in types %}
                <option value="{{type.0}}">{{type.0}}</option>
                {% endfor %}
            </select>
         
            <input id="id_date" name="date" type="date" />

            <button class="btn btn-danger d-block shadow" type="submit" >Search</button>

    </form>
</div>


{% if Trains.0 %}
    <h4 class="text-center p-4 border-bottom border-top">All trains available</h4>

 {% else %}
    <h4 class="text-center p-4 border-bottom border-top">Oops! Nothing found</h4>
 
{% endif %}

<div class="search_result row d-flex justify-content-around">
    {% for train in Trains %}
    <div class="card col-md-4 m-4 bg-warning text-light shadow" >
        <div class="card-body">
            <h5 class="card-title">{{train.source}} to {{train.destination}}</h5>
            <p class="card-text ">{{train.types}}</p>
            <p class="d-inline">{{train.date}}</p>
            <a class="d-inline" href='{% url "trains" train.id %}'>
                <button type="button" class="btn btn-dark">
                    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                    BOOK

            </button>
            </a>
        </div>
    </div>
    {% endfor %}
</div>


<script>

document.getElementById('id_date').valueAsDate = new Date();

var t1 = document.getElementById('id_source').value
if(t1 != ''){
console.log(t1)
}

</script>
{% endblock content %}